"""rename department

Revision ID: 222d17a7177e
Revises: 496601c2165e
Create Date: 2024-02-12 14:11:13.982029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222d17a7177e'
down_revision = '496601c2165e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
